default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: recipe/meta.yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo:  https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Respect `exclude` and `extend-exclude` settings.
        # args: ["--force-exclude"]
      - id: ruff-format
        args: [--check]
