name: lectorpy310
channels:
  - conda-forge
dependencies:
  - cchardet
  - gdown
  - humanize
  - rich
  - typer
  - pandas
  - pyarrow>=8.0.0
  - python=3.10
  - pip
  - pip:
    - clevercsv<0.8.1
    - lector @ git+https://github.com/graphext/lector@main
